
export enum UserRole {
  MASTER = 'master',
  MANAGER = 'gerente',
  FINANCE = 'financeiro',
  OPERATOR = 'operador'
}

export interface User {
  id: string;
  username: string;
  password?: string;
  storeName: string;
  adminName: string;
  role: UserRole;
  active: boolean;
}

export interface Subgroup {
  id: string;
  name: string;
}

export interface CostCenter {
  id: string;
  name: string;
  subgroups: Subgroup[];
}

export interface PaymentMethod {
  id: string;
  name: string;
}

export enum TransactionType {
  ENTRY = 'Entrada',
  EXIT = 'Saída'
}

export interface Transaction {
  id: string;
  date: string;
  type: TransactionType;
  amount: number;
  costCenterId: string;
  subgroupId: string;
  paymentMethodId: string;
  description: string;
  monthRef: string; // YYYY-MM
  createdBy: string; // User ID who created this
  creditSaleId?: string; // Link to credit sale if generated by one
}

export interface StoreCreditSale {
  id: string;
  clientCode: string;
  client: string;
  totalAmount: number;
  downPayment: number;
  downPaymentPaymentMethodId?: string;
  saleDate: string;
  monthRef: string;
  createdBy: string; // User ID who created this
}

export interface AppState {
  users: User[];
  costCenters: CostCenter[];
  paymentMethods: PaymentMethod[];
  transactions: Transaction[];
  creditSales: StoreCreditSale[];
}
